## Fit lw model ################################################################
#' @title Function that calls the model fitting procedure
#' @description This function prepares the input and calls the model fitting
#' function.
#'
#' @param dat length-weight data generated by `clean_data()`
#' @param length_to_predict vector of lengths to predict, default
#' is every 10 cm from the rounded 5th to the 95th percentile of the observed
#' lengths
#' @param year_to_predict vector of years to predict, default is the range of
#' years in `dat`
#' @param model_effects character vector of names of effects to estimate. Valid names
#' are: "no effects", "gut", "loc", "year", "week", "year-week".
#' @param inits initial parameter values
#' @param map list of parameters to map to initial values
#' @param do_rep logical indicating whether to run `obj$report()` on model
#' @param do_sdrep logical indicating whether to run `sdreport()` on model
#' @param check_estim logical indicating whether to do additional checking
#' of estimability using `TMBhelper::check_estimability(obj)`. This may be
#' useful if the model does not converge.
#' @param silent logical indicating wheter to supress output of optimizer
#' @param test numeric vector of sample ids to hold out of fit and predict

fit_lw <- function(dat, 
                   length_to_predict = NULL,
                   year_to_predict = NULL,
                   model_effects = NULL,
                   model_name = NULL,
                   inits = NULL,
                   map = list(),
                   do_rep = TRUE,
                   do_sdrep = FALSE,
                   check_estim = FALSE,
                   silent = FALSE,
                   test = NULL,
                   reduce_output = FALSE,
                   increase_evals = FALSE,
                   sdrep_pred = NULL
                   ) {
  
  valid_effect_names <- c("no effects", "gut", "loc", "year", "week", 
                          "year-week", "semester", "quarter", "month",
                          "year-semester", "year-quarter", "year-month",
                          "harmonic")
  
  # Check if any effect names are invalid
  if(any(!(model_effects %in% valid_effect_names))) {
    
    bad_names <- model_effects[which(!(model_effects %in% valid_effect_names))]
    
    stop(paste0("Invalid effect name(s): ", paste(bad_names, collapse = " "), " 
  Valid effect names are: ", 
                paste(valid_effect_names, collapse = " ")))
  }
  
  test  <<- test
  
  sdrep_pred <<- sdrep_pred
  
  if(is.null(year_to_predict)){
    year_to_predict <- min(dat$YEAR):max(dat$YEAR)  
  }
  
  if("gut" %in% model_effects & 
     (length(unique(dat$ind_gutted)) == 1) &
     (is.null(inits$log_g) | is.null(inits$log_a))) {
    stop(paste0("You are requesting a gutting effect but the dataset contains only ",
                ifelse(unique(dat$ind_gutted == 1), "gutted fish. ", "whole fish.")),
         "Therefore, the model cannot estimate the gutting effect. ",
         "If you still want a gutting effect (perhaps for a ", 
         "lodo exercise), you must set inits$log_g and inits$log_a to their ",
         "desired values and they will be held there.")
  }
  
  n_w <- 52 # number of weeks in a year
  n_i   <- nrow(dat)
  n_loc <- length(unique(dat$LOC))# Number of statistical areas
  n_y   <- length(year_to_predict)
  
  
  
  ind_year_to_predict <- 1:n_y
  
  week_to_predict <- 1:n_w
  ind_week_to_predict <- 1:n_w
  
  #if(is.null(loc_to_predict)) {
    loc_to_predict <- dat$LOC %>% unique %>% sort
  #}
  ind_loc_to_predict <- 1:length(loc_to_predict)
  
  
  if (is.null(length_to_predict)) {
    length_to_predict <- round(quantile(dat$Ltru_i, probs = c(0.10, 0.50, 0.90), na.rm = TRUE))
    
    # Optional: Ensure the values are unique in case rounding causes overlaps
    length_to_predict <- unique(as.numeric(length_to_predict))
  }
  
  if (!is.null(sdrep_pred$length)) {
    # Find lengths in sdrep_pred that are NOT already in length_to_predict
    new_lengths <- setdiff(sdrep_pred$length, length_to_predict)
    
    # If there are any new ones, append them
    if (length(new_lengths) > 0) {
      length_to_predict <- c(length_to_predict, new_lengths)
    }
  }
  
  pred_specs <<- 
    expand.grid(length_to_predict = length_to_predict,
                loc_to_predict  = loc_to_predict,
                week_to_predict = week_to_predict,
                year_to_predict = year_to_predict) %>%
    left_join(data.frame(year_to_predict, ind_year_to_predict)) %>%
    left_join(data.frame(week_to_predict, ind_week_to_predict)) %>%
    left_join(data.frame(loc_to_predict, ind_loc_to_predict)) %>%
    mutate(yw_to_predict = as.Date(paste(year_to_predict, week_to_predict, 
                                         "1", sep = "-"), format = "%Y-%U-%u")) %>%
    group_by(yw_to_predict) %>%
    mutate(ind_yw_to_predict = cur_group_id()) %>%
    suppressMessages()

  
 
  
  parameters <- list(
    log_a = if(!is.null(inits$log_a)) inits$log_a else 1e-05,
    log_b0 = if(!is.null(inits$log_b0)) inits$log_b0 else 1,
    log_sd_s = if(!is.null(inits$log_sd_s)) inits$log_sd_s else
                      rep(log(0.05), max(dat$ind_data_source))
  )
  
  random <- c()
   
  if ("gut" %in% model_effects) {
    parameters$log_g <- if(!is.null(inits$log_g)) inits$log_g  else log(1)
  }
  if("loc" %in% model_effects) {
    parameters$d_loc  = if(!is.null(inits$d_loc)) inits$d_loc else rep(0, n_loc)
    parameters$log_sd_d_loc = if(!is.null(inits$log_sd_d_loc)) inits$log_sd_d_loc else -2
    random <- c(random, "d_loc")
  }
  if(any(c("year") %in% model_effects)) {
    parameters$d_y = if(!is.null(inits$d_y)) inits$d_y else rep(log(1), n_y)
    parameters$log_sd_d_y = if(!is.null(inits$log_sd_d_y)) inits$log_sd_d_y else -2
    parameters$t_phi_y = if(!is.null(inits$t_phi_y)) inits$t_phi_y else 40
    random <- c(random, "d_y")
  }
  if(any(c("week") %in% model_effects)) {
    parameters$d_w = if(!is.null(inits$d_w)) inits$d_w else rep(log(1), n_w)
    parameters$log_sd_d_w = if(!is.null(inits$log_sd_d_w)) inits$log_sd_d_w else -10
    parameters$t_phi_w = if(!is.null(inits$t_phi_w)) inits$t_phi_w else 40
    random <- c(random, "d_w")
  }
  if(any(c("year-week") %in% model_effects)) {
    parameters$d_yw = if(!is.null(inits$d_yw)) inits$d_yw else rep(log(1), n_y*n_w)
    parameters$log_sd_d_yw = if(!is.null(inits$log_sd_d_yw)) inits$log_sd_d_yw else -10
    parameters$t_phi_yw = if(!is.null(inits$t_phi_yw)) inits$t_phi_yw else 40
    random <- c(random, "d_yw")
  }
  if(any(c("semester") %in% model_effects)) {
    parameters$d_sem <- if(!is.null(inits$d_sem)) inits$d_sem else log(1)
  }
  if(any(c("year-semester") %in% model_effects)) {
    parameters$d_ys = if(!is.null(inits$d_ys)) inits$d_ys else rep(log(1), n_y*2)
    parameters$log_sd_d_ys = if(!is.null(inits$log_sd_d_ys)) inits$log_sd_d_ys else -10
    parameters$t_phi_ys = if(!is.null(inits$t_phi_ys)) inits$t_phi_ys else 40
    random <- c(random, "d_ys")
  }
  if(any(c("quarter") %in% model_effects)){
    parameters$d_q <- if(!is.null(inits$d_q)) inits$d_q else rep(log(1), 3)
  }
  if(any(c("year-quarter") %in% model_effects)) {
    parameters$d_yq = if(!is.null(inits$d_yq)) inits$d_yq else rep(log(1), n_y*4)
    parameters$log_sd_d_yq = if(!is.null(inits$log_sd_d_yq)) inits$log_sd_d_yq else -10
    parameters$t_phi_yq = if(!is.null(inits$t_phi_yq)) inits$t_phi_yq else 40
    random <- c(random, "d_yq")
  }
  if(any(c("month") %in% model_effects)) {
    parameters$d_m = if(!is.null(inits$d_m)) inits$d_m else rep(log(1), 12)
    parameters$log_sd_d_m = if(!is.null(inits$log_sd_d_m)) inits$log_sd_d_m else -10
    parameters$t_phi_m = if(!is.null(inits$t_phi_m)) inits$t_phi_m else 40
    random <- c(random, "d_m")
  }
  if(any(c("year-month") %in% model_effects)) {
    parameters$d_ym = if(!is.null(inits$d_ym)) inits$d_ym else rep(log(1), n_y*12)
    parameters$log_sd_d_ym = if(!is.null(inits$log_sd_d_ym)) inits$log_sd_d_ym else -10
    parameters$t_phi_ym = if(!is.null(inits$t_phi_ym)) inits$t_phi_ym else 40
    random <- c(random, "d_ym")
  }
  if(any(c("harmonic") %in% model_effects)) {
    parameters$d_ah = if(!is.null(inits$d_ah)) inits$d_ah else rep(log(1), n_y)
    parameters$d_bh = if(!is.null(inits$d_bh)) inits$d_bh else rep(log(1), n_y)
    parameters$log_sd_d_ah = if(!is.null(inits$log_sd_d_ah)) inits$log_sd_d_ah else -10
    parameters$log_sd_d_bh = if(!is.null(inits$log_sd_d_bh)) inits$log_sd_d_bh else -10
    parameters$t_phi_ah = if(!is.null(inits$t_phi_ah)) inits$t_phi_ah else 40
    parameters$t_phi_bh = if(!is.null(inits$t_phi_bh)) inits$t_phi_bh else 40
    random <- c(random, "d_ah", "d_bh")
  }
  
  # just random walk for now:
  if("year" %in% model_effects) {
    map$t_phi_y <- factor(NA)
  }
  if("week" %in% model_effects) {
    map$t_phi_w <- factor(NA)
  }
  if("year-week" %in% model_effects) {
    map$t_phi_yw <- factor(NA)
  }
  if("month" %in% model_effects) {
    map$t_phi_m <- factor(NA)
  }
  if("year-semester" %in% model_effects) {
    map$t_phi_ys <- factor(NA)
  }
  if("year-quarter" %in% model_effects) {
    map$t_phi_yq <- factor(NA)
  }
  if("year-month" %in% model_effects) {
    map$t_phi_ym <- factor(NA)
  }
  if("harmonic" %in% model_effects) {
    map$t_phi_ah <- factor(NA)
    map$t_phi_bh <- factor(NA)
  }
  
  ind_b <- 
    expand.grid(ind_loc  = pred_specs$ind_loc_to_predict %>% unique %>% sort,
                ind_year = pred_specs$ind_year_to_predict %>% unique %>% sort,
                ind_week = pred_specs$ind_week_to_predict %>% unique %>% sort) %>%
    group_by(ind_year, ind_week) %>%
    mutate(ind_yw = cur_group_id()) %>%
    ungroup() %>%
    left_join(data.frame(ind_loc = pred_specs$ind_loc_to_predict %>% unique %>% sort,
                         LOC     = pred_specs$loc_to_predict %>% unique %>% sort)) %>%
    left_join(data.frame(ind_year = pred_specs$ind_year_to_predict %>% unique %>% sort,
                         YEAR     = pred_specs$year_to_predict %>% unique %>% sort)) %>%
    left_join(data.frame(ind_week = pred_specs$week_to_predict %>% unique %>% sort,
                         WEEK     = pred_specs$week_to_predict %>% unique %>% sort)) %>%
    left_join(data.frame(ind_yw   = pred_specs$ind_yw_to_predict %>% unique %>% sort,
                         YW       = pred_specs$yw_to_predict %>% unique %>% sort)) %>%
    left_join(tibble(WEEK = pred_specs$week_to_predict %>% unique %>% sort,
                     SEMESTER = ifelse(WEEK < 27, 1, 2),
                     ind_sem2 = (SEMESTER == 2))) %>%
    left_join(tibble(YW       = pred_specs$yw_to_predict %>% unique %>% sort,
                     QUARTER = lubridate::quarter(YW),
                     ind_q2  = (QUARTER == 2),
                     ind_q3  = (QUARTER == 3),
                     ind_q4  = (QUARTER == 4))) %>%
    left_join(tibble(YW = pred_specs$yw_to_predict %>% unique %>% sort,
                     MONTH = lubridate::month(YW),
                     ind_m = MONTH)) %>%
    mutate(YS = as.Date(paste(YEAR, 1 + (SEMESTER - 1)*6, "1", sep ="-")),
           YQ = as.Date(paste(YEAR, 1 + (QUARTER - 1)*3,  "1", sep ="-")),
           YM = as.Date(paste(YEAR, MONTH,   "1", sep ="-"))) %>%
    group_by(YS) %>%
    mutate(ind_ys = cur_group_id()) %>%
    group_by(YQ) %>%
    mutate(ind_yq = cur_group_id()) %>%
    group_by(YM) %>%
    mutate(ind_ym = cur_group_id()) %>%
    ungroup() %>%
    suppressMessages() %>%
    select(-YEAR, -WEEK, -SEMESTER, -QUARTER, -MONTH) # remove conflicts in getAll
  
  ind_use <- list()
  ind_use$b_Ltru_i <- match(paste(dat$LOC, dat$YW), paste(ind_b$LOC, ind_b$YW))
  ind_use$b_pred <- match(paste(pred_specs$ind_loc_to_predict, pred_specs$ind_yw_to_predict), 
                              paste(ind_b$ind_loc, ind_b$ind_yw))
  if (!is.null(test)) {
    dat_test <- dat[dat$s %in% test$s_test,]
    ind_use$b_test <- match(paste(dat_test$LOC, dat_test$YW), paste(ind_b$LOC, ind_b$YW))
  }
  
    
  ind_b <<- ind_b %>% select(-LOC, -YW) # remove conflicts in getAll
  
  ind_use <<- ind_use
  
  
  obj <- MakeADFun(cmb(model, dat),
                   parameters = parameters, 
                   random = random, 
                   map = map, 
                   silent = silent)
  
  control_list <- list()
  if(increase_evals) control_list <- list(eval.max = 2000, iter.max = 1000)
  opt <- nlminb(obj$par, obj$fn, obj$gr, 
                 control = control_list)
  
  if(check_estim) {
    tryCatch(checked_estim <- TMBhelper::check_estimability(obj), 
             error = function(e) {
               print(sdreport(obj))
               #stop(
               message(paste0("Some gradients are high.",
                              " Problematic parameters my be those above ",
                              "that are hitting bounds and/or have high Std. Errors."))
               
               #)
               
             })  
    if(exists("checked_estim") && !is.null(checked_estim$BadParams)) {
      
      #stop(
      message(paste0("The model may have some confounding of parameters.", 
                     " Consider a simplified model",
                     " that does not try to estimate one of the ",
                     shQuote("bad", "cmd"), " parameters above."))
        #)
    }
  }
  
  
  out <- list(obj = obj, opt = opt, 
              model_effects = model_effects, 
              model_name = model_name, 
              rep = NULL, pl = NULL, plsd = NULL, pred_specs = pred_specs)
  
  if(!is.null(test)) out$test <- test
  
  if(do_rep) out$rep <- obj$report()
  
  if (do_sdrep) { 
        sdrep <- sdreport(obj, getReportCovariance = FALSE)
        
        out$pl <- as.list(sdrep, "Est", report=TRUE)
        out$plsd <- as.list(sdrep, "Std", report=TRUE)
        out$pdHess <- sdrep$pdHess
        out$sdrep_pred <- sdrep_pred
  }
  
  if(reduce_output) {
    reduced_out <- list(
      # rep must be at the top level
      rep = list(
        unique_test_s = out$rep$unique_test_s,
        pred_Wobs_s_test = out$rep$pred_Wobs_s_test
      ),
      # test must be at the top level for pull_crossval_out
      test = list(
        fold = out$test$fold,           
        test_type = out$test$test_type  
      ),
      # opt must be at the top level for the convergence check
      opt = list(
        convergence = out$opt$convergence
      ),
      # Global variables used by pull_crossval_out
      model_effects = out$model_effects, 
      model_name = out$model_name,
      is_tscv = out$is_tscv
    )
    
    rm(out)
    gc() 
    
    return(reduced_out)
  } else return(out)
  
  
}




